const accountFields = [
  {
    label: "First Name",
    name: "givenName",
    id: "givenName",
    type: "text",
    className: "input-layout-control",
    fieldset: "account-form-input-fieldset",
    noValueError: "You must provide a first name.",
  },
  {
    label: "Last Name",
    name: "familyName",
    id: "familyName",
    type: "text",
    className: "input-layout-control",
    fieldset: "account-form-input-fieldset",
    noValueError: "You must provide a last name.",
  },
  {
    label: "Street Address",
    name: "address1",
    id: "address1",
    type: "text",
    className: "input-layout-control",
    fieldset: "account-form-input-fieldset",
    noValueError: "You must provide an address.",
  },
  {
    label: "Apt, Suite, Building",
    name: "address2",
    id: "address2",
    type: "text",
    className: "input-layout-control",
    fieldset: "account-form-input-fieldset",
    noValueError: null,
  },
  {
    label: "City",
    name: "locality",
    id: "locality",
    type: "text",
    className: "input-layout-control-sub",
    fieldset: "account-form-input-fieldset-sub",

    noValueError: "You must provide recipient(s).",
  },
  {
    label: "State",
    name: "province",
    id: "province",
    type: "text",
    className: "input-layout-control-sub",
    fieldset: "account-form-input-fieldset-sub",
    noValueError: "You must provide recipient(s).",
  },
  {
    label: "Zip",
    name: "code",
    id: "code",
    type: "text",
    className: "input-layout-control-sub",
    fieldset: "account-form-input-fieldset-sub",
    noValueError: "You must provide recipient(s).",
  },
  {
    label: "Country/Region:",
    name: "country",
    id: "country",
    type: "text",
    className: "input-layout-control-sub",
    fieldset: "account-form-input-fieldset-sub",
    noValueError: "You must provide recipient(s).",
  },
];

export default accountFields;
